version: "3.8"

services:
  # API Backend Service
  agendamento-cw-api:
    image: agendamento-cw-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    
    networks:
      - odmaxnet

    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Sao_Paulo
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - N8N_WEBHOOK_URL=https://webhookn8n.odtravel.com.br/webhook/default
      - N8N_ALERT_WEBHOOK_URL=https://n8n.odtravel.com.br/webhook-test/default
      - GEMINI_API_KEY=AIzaSyD_lF9jCzGKoT2fB5apsiNbGBq7fJj8T5I
      - CORS_ORIGIN=*

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.2"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=odmaxnet"
        - "traefik.http.routers.agendamento-cw-api.rule=Host(`apiag.odmax.com.br`)"
        - "traefik.http.routers.agendamento-cw-api.entrypoints=websecure"
        - "traefik.http.routers.agendamento-cw-api.tls=true"
        - "traefik.http.routers.agendamento-cw-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.agendamento-cw-api.loadbalancer.server.port=3000"
        - "traefik.http.routers.agendamento-cw-api.middlewares=api-headers"
        - "traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

  # Frontend Build and Serve Service
  agendamento-cw-frontend:
    image: agendamento-cw-frontend:latest
    build:
      context: ./chatwoot-message-scheduler
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://apiag.odmax.com.br/api

    networks:
      - odmaxnet

    environment:
      - VITE_API_BASE_URL=https://apiag.odmax.com.br/api
      - VITE_N8N_ALERT_WEBHOOK_URL=https://n8n.odtravel.com.br/webhook-test/default

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=odmaxnet"
        - "traefik.http.routers.agendamento-cw-frontend.rule=Host(`agendamento.odmax.com.br`)"
        - "traefik.http.routers.agendamento-cw-frontend.entrypoints=websecure"
        - "traefik.http.routers.agendamento-cw-frontend.tls=true"
        - "traefik.http.routers.agendamento-cw-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.agendamento-cw-frontend.loadbalancer.server.port=80"
        - "traefik.http.routers.agendamento-cw-frontend.middlewares=frontend-headers"
        - "traefik.http.middlewares.frontend-headers.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  odmaxnet:
    external: true
    name: odmaxnet