version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000" # Expose API on host port 3001
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./chatwoot-message-scheduler
      dockerfile: Dockerfile
    command: npm run dev -- --host
    volumes:
      - ./chatwoot-message-scheduler:/app
      - /app/node_modules
    ports:
      - "5173:5173" # Vite default port
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
