version: "3.7"

services:
  agendamento-cw-api:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        echo 'Installing git and cloning repository...' &&
        apk add --no-cache git curl &&
        git clone https://github.com/CaioGranato/agendamento_cw.git /tmp/repo &&
        cp -r /tmp/repo/api/* /app/ &&
        echo 'Installing dependencies...' &&
        npm install --production --no-optional &&
        echo 'Starting server...' &&
        npm start
      "
    
    networks:
      - odmaxnet

    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:66f26cf0a1b545cfb04266ee8c678016@postgres:5432/postgres
      - N8N_WEBHOOK_URL=https://webhookn8n.odtravel.com.br/webhook/71686ca7-d62c-43ed-8d6b-9930609ef6a9
      - N8N_ALERT_WEBHOOK_URL=https://webhookn8n.odtravel.com.br/webhook/alert-webhook-id
      - GEMINI_API_KEY=AIzaSyD_lF9jCzGKoT2fB5apsiNbGBq7fJj8T5I
      - CORS_ORIGIN=*
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.2"
          memory: 256M
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=odmaxnet"
        - "traefik.http.routers.agendamento-cw-api.rule=Host(`apiag.odmax.com.br`)"
        - "traefik.http.routers.agendamento-cw-api.entrypoints=websecure"
        - "traefik.http.routers.agendamento-cw-api.tls=true"
        - "traefik.http.routers.agendamento-cw-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.agendamento-cw-api.loadbalancer.server.port=3000"

  # Novo serviço para construir o frontend
  agendamento-cw-frontend:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        echo 'Installing git and cloning repository...' &&
        apk add --no-cache git curl &&
        git clone https://github.com/CaioGranato/agendamento_cw.git /tmp/repo &&
        cp -r /tmp/repo/chatwoot-message-scheduler/* /app/ &&
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Creating .env file...' &&
        echo 'API_BASE_URL=https://apiag.odmax.com.br/api' > .env &&
        echo 'N8N_ALERT_WEBHOOK_URL=${N8N_ALERT_WEBHOOK_URL}' >> .env &&
        echo 'Building frontend...' &&
        npm run build
      "
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://apiag.odmax.com.br/api
      - N8N_ALERT_WEBHOOK_URL=${N8N_ALERT_WEBHOOK_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - odmaxnet
    volumes:
      - frontend_build:/app/dist

networks:
  odmaxnet:
    external: true
    name: odmaxnet

volumes:
  frontend_build: