version: "3.7"

services:
  agendamento-cw-api:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        echo 'Installing git and cloning repository...' &&
        apk add --no-cache git curl &&
        git clone https://github.com/CaioGranato/agendamento_cw.git /tmp/repo &&
        cp -r /tmp/repo/api/* /app/ &&
        echo 'Installing dependencies...' &&
        npm install --production --no-optional &&
        echo 'Starting server...' &&
        npm start
      "
    
    networks:
      - your-network

    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGIN=*
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.2"
          memory: 256M
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=your-network"
        - "traefik.http.routers.agendamento-cw-api.rule=Host(`your-api-domain.com`)"
        - "traefik.http.routers.agendamento-cw-api.entrypoints=websecure"
        - "traefik.http.routers.agendamento-cw-api.tls=true"
        - "traefik.http.routers.agendamento-cw-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.agendamento-cw-api.loadbalancer.server.port=3000"

networks:
  your-network:
    external: true
    name: your-network