
    name: Build and Push Docker Images

    on:
      push:
        branches: [ "main" ] # Ou o nome da sua branch principal

    jobs:
      build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push API image
            uses: docker/build-push-action@v4
            with:
              context: ./api
              file: ./api/Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/agendamento-cw-api:latest

          - name: Build and push Frontend image
            uses: docker/build-push-action@v4
            with:
              context: ./chatwoot-message-scheduler
              file: ./chatwoot-message-scheduler/Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/agendamento-cw-frontend:latest
              build-args: |
                VITE_API_BASE_URL=https://apiag.odmax.com.br/api
    