name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./chatwoot-message-scheduler
        push: true
        tags: |
          granatocaio/agendamento-cw-frontend:latest
          granatocaio/agendamento-cw-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push API
      uses: docker/build-push-action@v5
      with:
        context: ./api
        push: true
        tags: |
          granatocaio/agendamento-cw-api:latest
          granatocaio/agendamento-cw-api:${{ github.sha }}
        no-cache: true